### ISSUE TITLE
circuit breaker 설정하기

### ISSUE THREAD

**Issue by jhhong0509** [team-xquare/v1-gateway#3]
### Describe

Circuit Breaker 설정하기

### Work

아직 모름

### Additional

아직 모름

**Comment by leeseojune53** [comment]
Fall-Back Messaging은 어떤가요??

**Comment by jhhong0509** [comment]
FallBack Messaging은 강결합의 위험이 있어 Circuit Breaker를 사용하는걸로 했습니당

**Comment by leeseojune53** [comment]
만약에 service mesh로 isto-envoy쓰면 envoy에서 하믄 되는디

**Comment by jhhong0509** [comment]
아하~~! 하지만 But. 우린 그걸 안쓴다..ㅠ
Istio 써보고싶긴 한데 후배의 후배 즈음 되면 적용하지 않을까
